"""
Tool: generate_report
----------------------
Generate professional PDF reports from order/inventory data or custom input.
Returns a publicly accessible PDF URL.

Requires: reportlab (pip install reportlab)
"""

from __future__ import annotations

import json
from datetime import datetime, timezone, date, timedelta
from pathlib import Path
from typing import Callable

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT


# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------

_DATA_ROOT   = Path(__file__).parent.parent / "data"
_REPORTS_DIR = _DATA_ROOT / "reports"
_ORDERS_DIR  = _DATA_ROOT / "orders"
_INV_DIR     = _DATA_ROOT / "inventory"


def _reports_dir(namespace: str) -> Path:
    d = _REPORTS_DIR / namespace
    d.mkdir(parents=True, exist_ok=True)
    return d


def _next_report_id(namespace: str) -> str:
    today = date.today().strftime("%Y%m%d")
    prefix = f"RPT-{today}-"
    d = _reports_dir(namespace)
    existing = [f.stem for f in d.glob(f"{prefix}*.pdf")]
    if existing:
        nums = [int(name.split("-")[-1]) for name in existing]
        seq = max(nums) + 1
    else:
        seq = 1
    return f"{prefix}{seq:03d}"


# ---------------------------------------------------------------------------
# i18n
# ---------------------------------------------------------------------------

_I18N = {
    "en": {
        "financial_report": "Financial Report",
        "inventory_report": "Inventory Report",
        "orders_report":    "Orders Report",
        "enrollment_report":"Enrollment Report",
        "custom_report":    "Report",
        "total_income":     "Total Income",
        "total_orders":     "Total Orders",
        "pending":          "Pending",
        "paid":             "Paid",
        "overdue":          "Overdue",
        "refunded":         "Refunded",
        "total_value":      "Total Value",
        "in_stock":         "In Stock",
        "low_stock":        "Low Stock",
        "out_of_stock":     "Out of Stock",
        "summary":          "Summary",
        "details":          "Details",
        "generated_by":     "Generated by ClawShow · clawshow.ai",
        "page":             "Page",
        "enrolled":         "Enrolled",
        "paid_tuition":     "Paid",
        "unpaid":           "Unpaid",
    },
    "fr": {
        "financial_report": "Rapport Financier",
        "inventory_report": "Rapport d'Inventaire",
        "orders_report":    "Rapport de Commandes",
        "enrollment_report":"Rapport d'Inscription",
        "custom_report":    "Rapport",
        "total_income":     "Revenu Total",
        "total_orders":     "Total Commandes",
        "pending":          "En attente",
        "paid":             "Payé",
        "overdue":          "En retard",
        "refunded":         "Remboursé",
        "total_value":      "Valeur Totale",
        "in_stock":         "En stock",
        "low_stock":        "Stock faible",
        "out_of_stock":     "Rupture",
        "summary":          "Résumé",
        "details":          "Détails",
        "generated_by":     "Généré par ClawShow · clawshow.ai",
        "page":             "Page",
        "enrolled":         "Inscrits",
        "paid_tuition":     "Payé",
        "unpaid":           "Impayé",
    },
    "zh": {
        "financial_report": "财务报告",
        "inventory_report": "库存报告",
        "orders_report":    "订单报告",
        "enrollment_report":"招生报告",
        "custom_report":    "报告",
        "total_income":     "总收入",
        "total_orders":     "总订单",
        "pending":          "待处理",
        "paid":             "已付款",
        "overdue":          "逾期",
        "refunded":         "已退款",
        "total_value":      "总价值",
        "in_stock":         "有货",
        "low_stock":        "库存低",
        "out_of_stock":     "缺货",
        "summary":          "摘要",
        "details":          "明细",
        "generated_by":     "由 ClawShow 生成 · clawshow.ai",
        "page":             "页",
        "enrolled":         "已注册",
        "paid_tuition":     "已缴费",
        "unpaid":           "未缴费",
    },
}

def _t(key: str, lang: str) -> str:
    return _I18N.get(lang, _I18N["en"]).get(key, _I18N["en"].get(key, key))


# ---------------------------------------------------------------------------
# Data loaders (read from orders/inventory JSON files)
# ---------------------------------------------------------------------------

def _load_orders(namespace: str, period: str = "", status: str = "", category: str = "") -> list[dict]:
    d = _ORDERS_DIR / namespace
    if not d.exists():
        return []
    orders = []
    for f in sorted(d.glob("ORD-*.json")):
        try:
            orders.append(json.loads(f.read_text(encoding="utf-8")))
        except Exception:
            pass

    if status and status != "all":
        orders = [o for o in orders if o.get("status") == status]
    if category:
        orders = [o for o in orders if o.get("category") == category]
    if period:
        orders = _filter_period(orders, period)
    return orders


def _load_inventory(namespace: str, categories: list | None = None, only_alerts: bool = False) -> list[dict]:
    d = _INV_DIR / namespace
    if not d.exists():
        return []
    items = []
    for f in sorted(d.glob("INV-*.json")):
        try:
            items.append(json.loads(f.read_text(encoding="utf-8")))
        except Exception:
            pass

    if categories:
        items = [i for i in items if i.get("category") in categories]
    if only_alerts:
        items = [i for i in items if i.get("quantity", 0) <= i.get("min_stock", 5)]
    return items


def _filter_period(items: list[dict], period: str) -> list[dict]:
    today = date.today()
    if period == "today":
        prefix = today.isoformat()
        return [i for i in items if i.get("created_at", "").startswith(prefix)]
    elif period == "week":
        start = (today - timedelta(days=today.weekday())).isoformat()
        return [i for i in items if i.get("created_at", "")[:10] >= start]
    elif period == "month":
        prefix = today.strftime("%Y-%m")
        return [i for i in items if i.get("created_at", "")[:7] == prefix]
    elif period == "quarter":
        q_month = ((today.month - 1) // 3) * 3 + 1
        prefix = f"{today.year}-{q_month:02d}"
        return [i for i in items if i.get("created_at", "")[:7] >= prefix]
    elif period == "year":
        prefix = str(today.year)
        return [i for i in items if i.get("created_at", "")[:4] == prefix]
    elif len(period) == 7:  # "2026-07"
        return [i for i in items if i.get("created_at", "")[:7] == period]
    return items


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------

_ACCENT_COLOR = colors.HexColor("#FF385C")
_GRAY         = colors.HexColor("#6B7280")
_LIGHT_BG     = colors.HexColor("#F9FAFB")


def _make_styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle("ReportTitle", parent=ss["Title"], fontSize=18, spaceAfter=6, textColor=colors.HexColor("#111827")))
    ss.add(ParagraphStyle("ReportSubtitle", parent=ss["Normal"], fontSize=10, textColor=_GRAY, spaceAfter=20))
    ss.add(ParagraphStyle("SectionHead", parent=ss["Heading2"], fontSize=13, textColor=colors.HexColor("#111827"), spaceBefore=16, spaceAfter=8))
    ss.add(ParagraphStyle("CellText", parent=ss["Normal"], fontSize=9, leading=12))
    ss.add(ParagraphStyle("FooterStyle", parent=ss["Normal"], fontSize=7, textColor=_GRAY, alignment=TA_CENTER))
    return ss


def _build_table(headers: list[str], rows: list[list], col_widths: list | None = None) -> Table:
    data = [headers] + rows
    t = Table(data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND",  (0, 0), (-1, 0), _ACCENT_COLOR),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTSIZE",    (0, 0), (-1, 0), 9),
        ("FONTSIZE",    (0, 1), (-1, -1), 8),
        ("ALIGN",       (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("GRID",        (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
    ]
    # Alternate row colors
    for i in range(1, len(data)):
        if i % 2 == 0:
            style.append(("BACKGROUND", (0, i), (-1, i), _LIGHT_BG))
    t.setStyle(TableStyle(style))
    return t


def _build_summary_table(kv_pairs: list[tuple[str, str]]) -> Table:
    data = [[k, v] for k, v in kv_pairs]
    t = Table(data, colWidths=[200, 200])
    style = [
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), _GRAY),
        ("FONTSIZE", (1, 0), (1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#E5E7EB")),
    ]
    t.setStyle(TableStyle(style))
    return t


def _footer_func(canvas, doc, text: str):
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_GRAY)
    canvas.drawCentredString(A4[0] / 2, 15 * mm, text)
    canvas.drawRightString(A4[0] - 20 * mm, 15 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _generate_pdf(namespace: str, title: str, subtitle: str, sections: list[dict], lang: str) -> tuple[str, str]:
    """Generate PDF, return (report_id, file_path)."""
    report_id = _next_report_id(namespace)
    out_path = _reports_dir(namespace) / f"{report_id}.pdf"
    ss = _make_styles()
    footer_text = _t("generated_by", lang)

    doc = SimpleDocTemplate(str(out_path), pagesize=A4,
                            topMargin=25 * mm, bottomMargin=25 * mm,
                            leftMargin=20 * mm, rightMargin=20 * mm)

    story: list = []
    story.append(Paragraph(title, ss["ReportTitle"]))
    story.append(Paragraph(subtitle, ss["ReportSubtitle"]))
    story.append(Spacer(1, 4 * mm))

    for sec in sections:
        if sec.get("title"):
            story.append(Paragraph(sec["title"], ss["SectionHead"]))
        if sec.get("content"):
            story.append(Paragraph(sec["content"], ss["Normal"]))
            story.append(Spacer(1, 3 * mm))
        if sec.get("summary_pairs"):
            story.append(_build_summary_table(sec["summary_pairs"]))
            story.append(Spacer(1, 4 * mm))
        if sec.get("table"):
            headers = sec["table"][0]
            rows = sec["table"][1:]
            story.append(_build_table(headers, rows, sec.get("col_widths")))
            story.append(Spacer(1, 4 * mm))

    doc.build(story, onFirstPage=lambda c, d: _footer_func(c, d, footer_text),
              onLaterPages=lambda c, d: _footer_func(c, d, footer_text))

    return report_id, str(out_path)


# ---------------------------------------------------------------------------
# Report type builders
# ---------------------------------------------------------------------------

def _report_financial(namespace: str, period: str, lang: str, title: str) -> tuple[str, str]:
    orders = _load_orders(namespace, period=period)
    title = title or f"{_t('financial_report', lang)} — {namespace}"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    total = sum(o.get("amount", 0) for o in orders)
    paid = sum(o.get("amount", 0) for o in orders if o.get("status") in ("paid", "completed"))
    pending = sum(o.get("amount", 0) for o in orders if o.get("status") in ("pending", "overdue"))

    # By category
    cats: dict[str, float] = {}
    for o in orders:
        c = o.get("category", "other")
        cats[c] = cats.get(c, 0) + o.get("amount", 0)

    sections = [
        {"title": _t("summary", lang), "summary_pairs": [
            (_t("total_orders", lang), str(len(orders))),
            (_t("total_income", lang), f"€{total:,.2f}"),
            (_t("paid", lang), f"€{paid:,.2f}"),
            (_t("pending", lang), f"€{pending:,.2f}"),
        ]},
        {"title": f"{_t('details', lang)} — Category", "table":
            [["Category", "Amount", "Orders"]] +
            [[c, f"€{v:,.2f}", str(len([o for o in orders if o.get("category", "other") == c]))] for c, v in sorted(cats.items())]
        },
    ]
    if orders:
        sections.append({"title": _t("details", lang), "table":
            [["Order", "Customer", "Amount", "Status", "Date"]] +
            [[o.get("order_id", ""), o.get("customer_name", ""), f"€{o.get('amount', 0):,.2f}",
              o.get("status", ""), o.get("created_at", "")[:10]] for o in orders[-50:]]
        })

    return _generate_pdf(namespace, title, f"Generated: {now} | Period: {period or 'all'}", sections, lang)


def _report_inventory(namespace: str, categories: list | None, only_alerts: bool, lang: str, title: str) -> tuple[str, str]:
    items = _load_inventory(namespace, categories, only_alerts)
    title = title or f"{_t('inventory_report', lang)} — {namespace}"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    total_val = sum(i.get("quantity", 0) * i.get("unit_cost", 0) for i in items)
    in_s = len([i for i in items if i.get("quantity", 0) > i.get("min_stock", 5)])
    low_s = len([i for i in items if 0 < i.get("quantity", 0) <= i.get("min_stock", 5)])
    out_s = len([i for i in items if i.get("quantity", 0) <= 0])

    sections = [
        {"title": _t("summary", lang), "summary_pairs": [
            ("Total Items", str(len(items))),
            (_t("total_value", lang), f"€{total_val:,.2f}"),
            (_t("in_stock", lang), str(in_s)),
            (_t("low_stock", lang), str(low_s)),
            (_t("out_of_stock", lang), str(out_s)),
        ]},
        {"title": _t("details", lang), "table":
            [["SKU", "Item", "Qty", "Min", "Unit Cost", "Value", "Status"]] +
            [[i.get("sku", ""), i.get("item_name", ""), str(i.get("quantity", 0)),
              str(i.get("min_stock", 5)), f"€{i.get('unit_cost', 0):.2f}",
              f"€{i.get('quantity', 0) * i.get('unit_cost', 0):.2f}",
              i.get("status", "")] for i in items]
        },
    ]

    return _generate_pdf(namespace, title, f"Generated: {now}", sections, lang)


def _report_orders(namespace: str, period: str, status: str, lang: str, title: str) -> tuple[str, str]:
    orders = _load_orders(namespace, period=period, status=status)
    title = title or f"{_t('orders_report', lang)} — {namespace}"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    total_amt = sum(o.get("amount", 0) for o in orders)
    by_status: dict[str, int] = {}
    for o in orders:
        s = o.get("status", "unknown")
        by_status[s] = by_status.get(s, 0) + 1

    sections = [
        {"title": _t("summary", lang), "summary_pairs":
            [(_t("total_orders", lang), str(len(orders))), (_t("total_income", lang), f"€{total_amt:,.2f}")] +
            [(s.title(), str(c)) for s, c in sorted(by_status.items())]
        },
        {"title": _t("details", lang), "table":
            [["Order ID", "Customer", "Amount", "Category", "Status", "Created"]] +
            [[o.get("order_id", ""), o.get("customer_name", ""), f"€{o.get('amount', 0):,.2f}",
              o.get("category", ""), o.get("status", ""), o.get("created_at", "")[:10]] for o in orders[-50:]]
        },
    ]

    return _generate_pdf(namespace, title, f"Generated: {now} | Period: {period or 'all'}", sections, lang)


def _report_enrollment(namespace: str, period: str, program: str, lang: str, title: str) -> tuple[str, str]:
    orders = _load_orders(namespace, period=period, category="tuition")
    if program:
        orders = [o for o in orders if program.lower() in o.get("description", "").lower()]
    title = title or f"{_t('enrollment_report', lang)} — {namespace}"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    enrolled = len(orders)
    paid_count = len([o for o in orders if o.get("status") in ("paid", "completed")])
    unpaid_count = enrolled - paid_count
    total_tuition = sum(o.get("amount", 0) for o in orders)
    paid_amount = sum(o.get("amount", 0) for o in orders if o.get("status") in ("paid", "completed"))

    sections = [
        {"title": _t("summary", lang), "summary_pairs": [
            (_t("enrolled", lang), str(enrolled)),
            (_t("paid_tuition", lang), f"{paid_count} (€{paid_amount:,.2f})"),
            (_t("unpaid", lang), f"{unpaid_count} (€{total_tuition - paid_amount:,.2f})"),
        ]},
        {"title": _t("details", lang), "table":
            [["Student", "Email", "Amount", "Status", "Date"]] +
            [[o.get("customer_name", ""), o.get("customer_email", ""), f"€{o.get('amount', 0):,.2f}",
              o.get("status", ""), o.get("created_at", "")[:10]] for o in orders]
        },
    ]

    return _generate_pdf(namespace, title, f"Generated: {now}", sections, lang)


def _report_custom(namespace: str, data: dict, user_sections: list, lang: str, title: str) -> tuple[str, str]:
    title = title or _t("custom_report", lang)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    sections = []
    for sec in user_sections:
        entry: dict = {}
        if sec.get("title"):
            entry["title"] = sec["title"]
        if sec.get("content"):
            entry["content"] = sec["content"]
        if sec.get("table"):
            entry["table"] = sec["table"]
        sections.append(entry)

    return _generate_pdf(namespace, title, f"Generated: {now}", sections, lang)


# ---------------------------------------------------------------------------
# Tool registration
# ---------------------------------------------------------------------------

def register(mcp, record_call: Callable) -> None:

    @mcp.tool()
    def generate_report(
        type: str,
        namespace: str,
        title: str = "",
        period: str = "",
        language: str = "en",
        include_income: bool = True,
        include_expenses: bool = True,
        include_chart: bool = True,
        categories: list | None = None,
        only_alerts: bool = False,
        status: str = "",
        program: str = "",
        data: dict | None = None,
        sections: list | None = None,
    ) -> str:
        """
        Generate professional PDF business reports and return a download URL.
        Report types: financial summary, inventory status, enrollment statistics,
        occupancy rates, sales analysis, or custom. Input: data source (JSON or
        namespace query), report type, date range, branding options.
        Output: PDF download URL. Reports include charts, tables, and executive
        summary. Ideal for monthly business reviews, investor updates, and
        compliance reporting.

        Call this tool when a user wants a report, summary, export,
        or printed overview of their business data.

        Examples:
        - 'Generate a financial report for florent this month'
        - 'Show me an inventory report for school-paris'
        - 'Create a PDF of all unpaid orders'
        - 'Export enrollment statistics for Fall 2026'
        - 'Fais-moi un rapport de toutes les commandes de juillet'

        Args:
            type:        "financial" | "inventory" | "orders" | "enrollment" | "custom"
            namespace:   Business namespace
            title:       Optional report title
            period:      "today" | "week" | "month" | "quarter" | "year" | "2026-07"
            language:    "en" | "fr" | "zh"
            categories:  Filter inventory categories
            only_alerts: Inventory: only low-stock items
            status:      Orders: filter by status
            program:     Enrollment: filter by program name
            data:        Custom: raw data
            sections:    Custom: section definitions

        Returns:
            JSON with report_url, report_id, title, type, generated_at.
        """
        record_call("generate_report")

        try:
            if type == "financial":
                report_id, path = _report_financial(namespace, period, language, title)
            elif type == "inventory":
                report_id, path = _report_inventory(namespace, categories, only_alerts, language, title)
            elif type == "orders":
                report_id, path = _report_orders(namespace, period, status, language, title)
            elif type == "enrollment":
                report_id, path = _report_enrollment(namespace, period, program, language, title)
            elif type == "custom":
                report_id, path = _report_custom(namespace, data or {}, sections or [], language, title)
            else:
                return json.dumps({"status": "error", "message": f"Unknown type: {type}. Use financial/inventory/orders/enrollment/custom."})

            # Count pages (rough: file size / ~2KB per page, minimum 1)
            file_size = Path(path).stat().st_size
            est_pages = max(1, file_size // 2048)

            report_url = f"https://mcp.clawshow.ai/reports/{namespace}/{report_id}.pdf"

            return json.dumps({
                "report_url": report_url,
                "report_id": report_id,
                "title": title or f"{type.title()} Report",
                "type": type,
                "pages": est_pages,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            }, ensure_ascii=False)

        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})
